rsocket.disabled: true

server:
  port: 9990

rsocket:
  brokers: tcp://127.0.0.1:9999
  port: 9991
  jwt-token: your_token_here

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always